Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -54,7 +54,7 @@ jobs:
         run: sleep 5
 
       - name: Run tests
-        run: python tests/test.py || (echo "Failed" >> error.txt && exit 1)
+        run: python tests/test.py > error.txt 2>&1 || (echo "Failed" >> error.txt && exit 1)
         
       - name: Report Bug on Azure
         if: failure()
