Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -54,11 +54,11 @@ jobs:
         run: sleep 5
 
       - name: Run tests
-        run: python tests/test.py 2>$1 || echo "Failed" >> errors.txt
+        run: python tests/test.py || echo "Failed" >> error.txt
         
       - name: Report Bug on Azure
         if: failure()
         run: |
           az devops configure --defaults organization=https://dev.azure.com/Petrashevich/ project=Test
           az devops login --organization https://dev.azure.com/Petrashevich/ --token ${{ secrets.AZURE_TOKEN }}
-          az devops work-item create --type Bug --title "Test Failure" --description "$(cat failure.txt)" --output json
+          az devops work-item create --type Bug --title "Test Failure" --description "$(cat error.txt)" --output json
